openapi: 3.0.0
info:
  title: Socket Protocol API
  description: API for interacting with Socket Protocol services
  version: 1.0.0
servers:
  - url: https://api-evmx-devnet.socket.tech
    description: Socket Protocol Devnet API Server
paths:
  /getDetailsByTxHash:
    get:
      summary: Get transaction details by transaction hash
      description: Retrieves detailed information about payloads associated with a transaction hash
      operationId: getDetailsByTxHash
      parameters:
        - name: txHash
          in: query
          required: true
          schema:
            type: string
          description: Transaction hash to query
          example: "0xaf92e0f81c6d384b39c04401abdf7d07bc2b784434facec8658dc5c06f65f76e"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  response:
                    type: array
                    items:
                      $ref: '#/components/schemas/FormattedRequestDetails'
              example: {
                "status": "SUCCESS",
                "response": [
                  {
                    "status": "COMPLETED",
                    "requestCount": 260,
                    "writePayloads": [],
                    "readPayloads": [
                      {
                        "payloadId": "0x6ea9df682fd227782ea250143d1322af2f83d9ba12c4e19ba4fe36987bfaa556",
                        "chainSlug": 421614,
                        "target": "0xd5ea574941b024fb3d4be542908bd67367d75137",
                        "batchCount": 378,
                        "callType": "READ",
                        "payload": "0x5e383d210000000000000000000000000000000000000000000000000000000000000008",
                        "simulationDetails": {
                          "executeSimulationStatus": "SIMULATION_SUCCESS",
                          "executeRevertString": "",
                          "callbackSimulationStatus": "SIMULATION_SUCCESS",
                          "callbackRevertString": ""
                        },
                        "executeDetails": {
                          "isExecuted": true,
                          "returnData": "0x0000000000000000000000000000000000000000000000000000000000000007"
                        },
                        "callBackDetails": {
                          "callbackTxHash": "0x3d566266f4552d89784e18659021abe8589ffff7eaae9d58bcfe4fc41f66d8c8",
                          "callbackStatus": "PROMISE_RESOLVED"
                        }
                      }
                    ]
                  }
                ]
              }
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /payload:
    get:
      summary: Get payload details
      description: Retrieves details for a specific payload by ID
      operationId: getPayloadDetails
      parameters:
        - name: payloadId
          in: query
          required: true
          schema:
            type: string
          description: ID of the payload to query
          example: "0xe878de8efff3688aaa2da0aecde6442e31e494621a1461355069b9b7b12b8c8b"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  response:
                    $ref: '#/components/schemas/Payload'
              example: {
                "status": "SUCCESS",
                "response": {
                  "id": 2222,
                  "payloadId": "0xe878de8efff3688aaa2da0aecde6442e31e494621a1461355069b9b7b12b8c8b",
                  "requestCount": 256,
                  "batchCount": 369,
                  "payloadCount": 653,
                  "asyncPromise": "0x0ecea1cF732ccb6F2b485Fd726bFA297a26947dC",
                  "chainSlug": 11155420,
                  "target": "0x853939f827a2a3ae7c27fd57783af1dea7a75885",
                  "payload": "0xe8927fbc",
                  "value": "0",
                  "appGateway": "0x2c3783588FFECD25F936AA036432D408CBFF057B",
                  "deadline": 1745572577,
                  "isParallel": false,
                  "writeFinality": 0,
                  "isReadAnchorBlockNumber": true,
                  "readAt": 0,
                  "finalizeTxHash": "0xcd95da822ff81dd2a3654922355e789adee6d00a511c4b366da94a93441d3bf5",
                  "finalizeStatus": "FINALIZED",
                  "isFinalized": true,
                  "executeTxHash": "0x2b7b03b99754a974da4b885004d2324daab815e900ac5120adf693f8552e3826",
                  "submitOrderTxHash": null,
                  "executeStatus": "EXECUTED",
                  "isExecuted": true,
                  "executeSimulationStatus": "NO",
                  "executeRevertString": null,
                  "callbackTxHash": "0x52af4b47e02b33d709fd7fd17fe4a5b54091e7caef410d50f268638a76d6caca",
                  "callbackStatus": "PROMISE_RESOLVED",
                  "callbackSimulationStatus": "SIMULATION_SUCCESS",
                  "callbackRevertString": "",
                  "isCallbackCompleted": true,
                  "callType": 1,
                  "returnData": "0x000000000000000000000000000000000000000000000000000000000000000d",
                  "proof": "0x36166ad86a4f8e5471f9f401f00b6d2c31c9332e49874d2e9cd331540e07e0f51301bf0def0e00a16b1fe9096d2a4994a21bbbbeef161f838c15fe761a035bcb1c",
                  "gasLimit": 10000000,
                  "estimatedGasLimit": null,
                  "digest": "0x682169aa7ce5b255e9b078f34a43fa979c79cfcaddd6e957723fdb39b8134a7f",
                  "switchboard": "0xd94741a4654953817faee228739a6d10c0683839",
                  "prevDigestsHash": "0x5b3110a56c258b59d9c2b743755ad7365bf2769d3b1e9179d7ac7ac117f6af41",
                  "createdAt": "2025-04-25T09:10:54.067Z",
                  "updatedAt": "2025-04-25T09:11:21.028Z"
                }
              }
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /getRequestDetails:
    get:
      summary: Get request details
      description: Retrieves details for a specific request by count
      operationId: getRequestDetails
      parameters:
        - name: requestCount
          in: query
          required: true
          schema:
            type: string
          description: Request count to query
          example: "260"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  response:
                    $ref: '#/components/schemas/Request'
              example: {
                "status": "SUCCESS",
                "response": {
                  "requestCount": 260,
                  "submitOrderTxHash": "0xaf92e0f81c6d384b39c04401abdf7d07bc2b784434facec8658dc5c06f65f76e",
                  "status": "COMPLETED",
                  "createdAt": "2025-04-25T09:10:54.067Z",
                  "updatedAt": "2025-04-25T09:11:21.028Z"
                }
              }
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /timeout:
    get:
      summary: Get timeout details
      description: Retrieves timeout details based on timeoutId, txHash, or target
      operationId: getTimeoutDetails
      parameters:
        - name: txHash
          in: query
          required: false
          schema:
            type: string
          description: Transaction hash to query
          example: "0x289e0a1cc4fb420f0cd700ac38495dccd35a146756e7c065b7a0f18d65a9695d"
        - name: timeoutId
          in: query
          required: false
          schema:
            type: string
          description: Timeout ID to query
          example: "0x0000002bebda834fac9ca4b86add442083c1650f8497edcb00000000000002c6"
        - name: target
          in: query
          required: false
          schema:
            type: string
          description: Target address to query
          example: "0xfc8520c008f1a9b05989f0773c0115839995c194"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  response:
                    type: array
                    items:
                      $ref: '#/components/schemas/Timeout'
              example: {
                "status": "SUCCESS",
                "response": [
                  {
                    "id": 686,
                    "timeoutId": "0x0000002bebda834fac9ca4b86add442083c1650f8497edcb00000000000002c6",
                    "target": "0xfc8520c008f1a9b05989f0773c0115839995c194",
                    "payload": "0xbaaa06f3000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000680b532c",
                    "executeAt": 1745577652,
                    "executedAt": null,
                    "isResolved": null,
                    "status": "ADDED_TO_QUEUE",
                    "resolveTxHash": null,
                    "simulationStatus": "NO",
                    "revertString": null,
                    "originTxHash": "0x289e0a1cc4fb420f0cd700ac38495dccd35a146756e7c065b7a0f18d65a9695d",
                    "createdAt": "2025-04-25T09:17:32.295Z",
                    "updatedAt": "2025-04-25T09:17:32.295Z"
                  }
                ]
              }
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /inbox:
    get:
      summary: Get inbox details
      description: Retrieves details for inbox transactions
      operationId: getInboxDetails
      parameters:
        - name: txHash
          in: query
          required: true
          schema:
            type: string
          description: Transaction hash to query
          example: "0xc48db420119faf3abd6417711bc80ed1435d506411ebd0ff9c42a95b6dc10735"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  response:
                    type: array
                    items:
                      $ref: '#/components/schemas/FormattedBatch'
              example: {
                "status": "SUCCESS",
                "response": [
                  {
                    "status": "Executed",
                    "onChainTxHash": "0xc48db420119faf3abd6417711bc80ed1435d506411ebd0ff9c42a95b6dc10735",
                    "callId": "0x00066eeecfd84fb831faca500101decab714ba9d8f012613000000000000000f",
                    "chainSlug": 421614,
                    "plug": "0x62e16f19ddcfb0fb30330d5e130da4f6b73d5432",
                    "payload": {
                      "appGateway": "0xcfd84fb831faca500101decab714ba9d8f012613",
                      "payload": "0x0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000005",
                      "params": "0x0000000000000000000000000000000000000000000000000000000000000000"
                    },
                    "ExecutionDetails": {
                      "appGatewayTxHash": "0xc6f4e87e88c7c6a17379564e7525464b337b702b2b68a723d71508666185257e",
                      "simulationStatus": "SIMULATION_SUCCESS",
                      "revertString": ""
                    }
                  }
                ]
              }
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
      example:
        error: "Invalid transaction hash"

    Status:
      type: string
      enum: [COMPLETED, IN_PROGRESS, REVERTING]

    FormattedRequestDetails:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Status'
        writePayloads:
          type: array
          items:
            $ref: '#/components/schemas/FormattedWritePayload'
        readPayloads:
          type: array
          items:
            $ref: '#/components/schemas/FormattedReadPayload'
        feeInfo:
          type: object
          properties:
            feePoolChain:
              type: integer
            feePoolToken:
              type: string
            feePoolTokenName:
              type: string
            maxFees:
              type: string
            fee:
              type: string
        requestCount:
          type: integer

    FormattedWritePayload:
      type: object
      properties:
        payloadId:
          type: string
        chainSlug:
          type: integer
        target:
          type: string
        batchCount:
          type: integer
        callType:
          type: string
        payload:
          type: string
        simulationDetails:
          type: object
          properties:
            executeSimulationStatus:
              type: string
            executeRevertString:
              type: string
            callbackSimulationStatus:
              type: string
              nullable: true
            callbackRevertString:
              type: string
              nullable: true
        finalizeDetails:
          type: object
          properties:
            finalizeTxHash:
              type: string
            finalizeStatus:
              type: string
        executeDetails:
          type: object
          properties:
            isExecuted:
              type: boolean
            executeTxHash:
              type: string
            executeStatus:
              type: string
            returnData:
              type: string
        callBackDetails:
          type: object
          properties:
            callbackTxHash:
              type: string
            callbackStatus:
              type: string
        deployerDetails:
          type: object
          properties:
            onChainAddress:
              type: string
            forwarderAddress:
              type: string
            isForwarderDeployed:
              type: boolean
      example:
        payloadId: "0x1cc09d4b5d6fc66447c7ef6551e1f0e576133f3b4924671105b64c77700531ee"
        chainSlug: 11155420
        batchCount: 356
        target: "0x853939f827a2a3ae7c27fd57783af1dea7a75885"
        callType: "WRITE"
        payload: "0xe8927fbc"
        simulationDetails:
          executeSimulationStatus: "NO"
          executeRevertString: null
          callbackSimulationStatus: "SIMULATION_SUCCESS"
          callbackRevertString: ""
        executeDetails:
          isExecuted: true
          executeTxHash: "0xde6f06c616ffe018ae492aaa638c42320dcbaa758150266dee813f2c9e8aa37f"
          executeStatus: "EXECUTED"
          returnData: "0x0000000000000000000000000000000000000000000000000000000000000003"
        callBackDetails:
          callbackTxHash: "0xed4a1ab8ef0558be6d900d76db8e47fbb6715e1f44b9b4b48c4f8233998eef96"
          callbackStatus: "PROMISE_RESOLVED"
        finalizeDetails:
          finalizeTxHash: "0x625fccf51cf5c289bd36a0066f671daa71eb21cabe70774565dc3731493d54f2"
          finalizeStatus: "FINALIZED"

    FormattedReadPayload:
      type: object
      properties:
        payloadId:
          type: string
        chainSlug:
          type: integer
        target:
          type: string
        batchCount:
          type: integer
        callType:
          type: string
        payload:
          type: string
        simulationDetails:
          type: object
          properties:
            executeSimulationStatus:
              type: string
            executeRevertString:
              type: string
            callbackSimulationStatus:
              type: string
              nullable: true
            callbackRevertString:
              type: string
              nullable: true
        executeDetails:
          type: object
          properties:
            isExecuted:
              type: boolean
            returnData:
              type: string
        callBackDetails:
          type: object
          properties:
            callbackStatus:
              type: string
            callbackTxHash:
              type: string
      example:
        payloadId: "0x6ea9df682fd227782ea250143d1322af2f83d9ba12c4e19ba4fe36987bfaa556"
        chainSlug: 421614
        target: "0xd5ea574941b024fb3d4be542908bd67367d75137"
        batchCount: 378
        callType: "READ"
        payload: "0x5e383d210000000000000000000000000000000000000000000000000000000000000008"
        simulationDetails:
          executeSimulationStatus: "SIMULATION_SUCCESS"
          executeRevertString: ""
          callbackSimulationStatus: "SIMULATION_SUCCESS"
          callbackRevertString: ""
        executeDetails:
          isExecuted: true
          returnData: "0x0000000000000000000000000000000000000000000000000000000000000007"
        callBackDetails:
          callbackTxHash: "0x3d566266f4552d89784e18659021abe8589ffff7eaae9d58bcfe4fc41f66d8c8"
          callbackStatus: "PROMISE_RESOLVED"

    Request:
      type: object
      properties:
        requestCount:
          type: integer
        submitOrderTxHash:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      example:
        requestCount: 260
        submitOrderTxHash: "0xaf92e0f81c6d384b39c04401abdf7d07bc2b784434facec8658dc5c06f65f76e"
        status: "COMPLETED"
        createdAt: "2025-04-25T09:10:54.067Z"
        updatedAt: "2025-04-25T09:11:21.028Z"

    Payload:
      type: object
      properties:
        id:
          type: integer
        payloadId:
          type: string
        requestCount:
          type: integer
        batchCount:
          type: integer
        payloadCount:
          type: integer
        asyncPromise:
          type: string
        chainSlug:
          type: integer
        target:
          type: string
        payload:
          type: string
        value:
          type: string
        appGateway:
          type: string
        deadline:
          type: integer
        isParallel:
          type: boolean
        writeFinality:
          type: integer
        isReadAnchorBlockNumber:
          type: boolean
        readAt:
          type: integer
        finalizeTxHash:
          type: string
        finalizeStatus:
          type: string
        isFinalized:
          type: boolean
        executeTxHash:
          type: string
        submitOrderTxHash:
          type: string
          nullable: true
        executeStatus:
          type: string
        isExecuted:
          type: boolean
        executeSimulationStatus:
          type: string
        executeRevertString:
          type: string
          nullable: true
        callbackTxHash:
          type: string
        callbackStatus:
          type: string
        callbackSimulationStatus:
          type: string
        callbackRevertString:
          type: string
        isCallbackCompleted:
          type: boolean
        callType:
          type: integer
        returnData:
          type: string
        proof:
          type: string
        gasLimit:
          type: integer
        estimatedGasLimit:
          type: integer
          nullable: true
        digest:
          type: string
        switchboard:
          type: string
        prevDigestsHash:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      example:
        id: 2222
        payloadId: "0xe878de8efff3688aaa2da0aecde6442e31e494621a1461355069b9b7b12b8c8b"
        requestCount: 256
        batchCount: 369
        payloadCount: 653
        asyncPromise: "0x0ecea1cF732ccb6F2b485Fd726bFA297a26947dC"
        chainSlug: 11155420
        target: "0x853939f827a2a3ae7c27fd57783af1dea7a75885"
        payload: "0xe8927fbc"
        value: "0"
        appGateway: "0x2c3783588FFECD25F936AA036432D408CBFF057B"
        deadline: 1745572577
        isParallel: false
        writeFinality: 0
        isReadAnchorBlockNumber: true
        readAt: 0
        finalizeTxHash: "0xcd95da822ff81dd2a3654922355e789adee6d00a511c4b366da94a93441d3bf5"
        finalizeStatus: "FINALIZED"
        isFinalized: true
        executeTxHash: "0x2b7b03b99754a974da4b885004d2324daab815e900ac5120adf693f8552e3826"
        submitOrderTxHash: null
        executeStatus: "EXECUTED"
        isExecuted: true
        executeSimulationStatus: "NO"
        executeRevertString: null
        callbackTxHash: "0x52af4b47e02b33d709fd7fd17fe4a5b54091e7caef410d50f268638a76d6caca"
        callbackStatus: "PROMISE_RESOLVED"
        callbackSimulationStatus: "SIMULATION_SUCCESS"
        callbackRevertString: ""
        isCallbackCompleted: true
        callType: 1
        returnData: "0x000000000000000000000000000000000000000000000000000000000000000d"
        proof: "0x36166ad86a4f8e5471f9f401f00b6d2c31c9332e49874d2e9cd331540e07e0f51301bf0def0e00a16b1fe9096d2a4994a21bbbbeef161f838c15fe761a035bcb1c"
        gasLimit: 10000000
        estimatedGasLimit: null
        digest: "0x682169aa7ce5b255e9b078f34a43fa979c79cfcaddd6e957723fdb39b8134a7f"
        switchboard: "0xd94741a4654953817faee228739a6d10c0683839"
        prevDigestsHash: "0x5b3110a56c258b59d9c2b743755ad7365bf2769d3b1e9179d7ac7ac117f6af41"
        createdAt: "2025-04-25T09:10:54.067Z"
        updatedAt: "2025-04-25T09:11:21.028Z"

    Timeout:
      type: object
      properties:
        id:
          type: integer
        timeoutId:
          type: string
        target:
          type: string
        payload:
          type: string
        executeAt:
          type: integer
        executedAt:
          type: integer
          nullable: true
        isResolved:
          type: boolean
          nullable: true
        status:
          type: string
        resolveTxHash:
          type: string
          nullable: true
        simulationStatus:
          type: string
        revertString:
          type: string
          nullable: true
        originTxHash:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      example:
        id: 686
        timeoutId: "0x0000002bebda834fac9ca4b86add442083c1650f8497edcb00000000000002c6"
        target: "0xfc8520c008f1a9b05989f0773c0115839995c194"
        payload: "0xbaaa06f3000000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000680b532c"
        executeAt: 1745577652
        executedAt: null
        isResolved: null
        status: "ADDED_TO_QUEUE"
        resolveTxHash: null
        simulationStatus: "NO"
        revertString: null
        originTxHash: "0x289e0a1cc4fb420f0cd700ac38495dccd35a146756e7c065b7a0f18d65a9695d"
        createdAt: "2025-04-25T09:17:32.295Z"
        updatedAt: "2025-04-25T09:17:32.295Z"

    InboxStatus:
      type: string
      enum: [NotTried, AddedToQueue, ExecutionFailing, Executing, Executed]

    FormattedBatch:
      type: object
      properties:
        status:
          type: string
        onChainTxHash:
          type: string
        callId:
          type: string
        chainSlug:
          type: integer
        plug:
          type: string
        payload:
          type: object
          properties:
            appGateway:
              type: string
            payload:
              type: string
            params:
              type: string
        ExecutionDetails:
          type: object
          properties:
            appGatewayTxHash:
              type: string
            simulationStatus:
              type: string
            revertString:
              type: string
      example:
        status: "Executed"
        onChainTxHash: "0xc48db420119faf3abd6417711bc80ed1435d506411ebd0ff9c42a95b6dc10735"
        callId: "0x00066eeecfd84fb831faca500101decab714ba9d8f012613000000000000000f"
        chainSlug: 421614
        plug: "0x62e16f19ddcfb0fb30330d5e130da4f6b73d5432"
        payload: {
          "appGateway": "0xcfd84fb831faca500101decab714ba9d8f012613",
          "payload": "0x0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000005",
          "params": "0x0000000000000000000000000000000000000000000000000000000000000000"
        }
        ExecutionDetails: {
          "appGatewayTxHash": "0xc6f4e87e88c7c6a17379564e7525464b337b702b2b68a723d71508666185257e",
          "simulationStatus": "SIMULATION_SUCCESS",
          "revertString": ""
        }
